from openai.error import OpenAIError

class InvalidEngineException(OpenAIError):
    pass
